### PR TITLE
Add support for "preprocessing" BCP:13 codes prior to validation

### PR DESCRIPTION
**Pull request by okeefm**
# Summary
BCP:13 codes (aka `MIME Types`) can have optional "parameters" tacked on after the actual MIME type; like `application/fhir+json; charset=UTF-8`. This is considered "legal" in FHIR, but our Bloom Filters can't handle them, so we have to strip off anything that's not the MIME type itself before validation.

While we're at it, this PR also `downcase`s the MIME type before validation, to avoid case mismatches (since MIIME types are case-insensitive). 

The PR also adds this preprocess step to the BCP:13 bloom filter generation code, so moving forward all the MIME types coming out of the MIME::types gem will be `downcase`d.

## Testing guidance
* Ensure the bloom filters are built/present on your system
* Test a MIME type with parameters against the appropriate valueset, with a Rake task like `rake terminology:check_code['application/fhir+json; CHARSET=utf-8','urn:ietf:bcp:13','http://hl7.org/fhir/ValueSet/mimetypes']`
* Optional: run the same task, but change the MIME type to be gibberish, and ensure the code check fails
* Optional: run the terminology build tasks (after deleting the bloom filters) and test a code like `application/A2L` (which is upcased coming from the `mime-types` gem) and ensure it passes both upcase'd and downcase'd

### CODE REVIEW

**Review by radamson — APPROVED** [review]
Code looks good and everything worked as expected testing locally.

Do we need to port this to `onc-healthit/inferno` too?

**Comment by okeefm** [comment]
@radamson Probably not. inferno-community is delegating all of its terminology to tx.fhir.org with a PR that's open now.

**Comment by okeefm** [comment]
Fixes #281

**Review by arscan — APPROVED** [review]
Looks good!

**Pull request merged**
