### PR TITLE
FI-762-767 Minor UI fix

### PR DESCRIPTION
**Pull request by yunwwang**
The Pull Request has two minor UI fix:
1) added missing end quote mark for invalidate content-type
2) added bullet points for error message.

**Submitter:**
- [x] This pull request describes why these changes were made
- [x] Internal ticket for this PR:
- [x] Internal ticket links to this PR
- [x] Internal ticket is properly labeled (Community/Program)
- [x] Internal ticket has a justification for its Community/Program label
- [x] Code diff has been reviewed for extraneous/missing code
- [x] Tests are included and test edge cases
- [x] Tests/code quality metrics have been run locally and pass

**Reviewer 1:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure
      where appropriate, and accomplishes the task's purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

**Reviewer 2:**

Name:
- [ ] Code is maintainable and reusable, reuses existing code and infrastructure
      where appropriate, and accomplishes the task's purpose
- [ ] The tests appropriately test the new code, including edge cases
- [ ] You have tried to break the code

### CODE REVIEW

**Comment by okeefm** [comment]
These look good from the code side. What's the easiest way to "break" the bulk data patients/responses to see these improved error messages?

**Comment by Jammjammjamm** [comment]
Could you add a screenshot to show what this looks like?

**Comment by yunwwang** [comment]
image
This is display in the result detail page

**Comment by yunwwang** [comment]
image
This is the display on the result list page

**Comment by yunwwang** [comment]
You can test using bulk-data.smarthealthit.org

**Pull request merged**
